name: 'Ebisu Action'
description: 'Ebisu action to panicking people hehe'
inputs:
  service-name:
    description: 'Service name'
    required: true
  message:
    description: 'Message that you want to send'
    required: true
  address:
    description: 'Ebisu Address'
    required: true
outputs:
  id:
    description: 'Message ID return by ebisu'
  
runs:
  using: 'node12'
  main: 'index.js'
